name: "Dev Build and Deploy"

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  tf-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    environment: dev 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Secrets
        run: |
          echo "ENV_NAME=${{github.ref_name}}" >> $GITHUB_ENV
          echo "TF_VAR_project=${{ secrets.GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 432.0.0"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Terraform FMT
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="prefix=${{ secrets.TF_STATE_PREFIX }}/${{ env.ENV_NAME }}"

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Setup and Run TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: terraform/.tflint.hcl
          cache: true # Caching helps speed up subsequent runs

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan -out=tfplan -input=false \
            -var="project=${{ env.TF_VAR_project }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="zone=${{ secrets.GCP_ZONE }}" \
            -var="environment=${{ env.ENV_NAME }}"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ env.ENV_NAME }}
          path: terraform/tfplan
    
  # await-approval:
  #   name: Await Manual Approval
  #   runs-on: ubuntu-latest
  #   needs: tf-plan
  #   environment: dev      # <-- set the Environment that requires your pr-approvers team
  #   steps:
  #     - name: Waiting for Approval
  #       run: echo "This Job Will Pause Until a Member of the PR-APPROVERS Group Accepts the Deployment."
  
  tf-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    # needs: await-approval
    needs: tf-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Secrets
        run: |
          echo "ENV_NAME=${{github.ref_name}}" >> $GITHUB_ENV
          echo "TF_VAR_project=${{ secrets.GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 432.0.0"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="prefix=${{ secrets.TF_STATE_PREFIX }}/${{ env.ENV_NAME }}"
      
      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan -out=tfplan -input=false \
            -var="project=${{ env.TF_VAR_project }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="zone=${{ secrets.GCP_ZONE }}" \
            -var="environment=${{ env.ENV_NAME }}"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -input=false -auto-approve tfplan-${{ env.ENV_NAME }}